language: php

php:
  - 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer require --dev --no-update squizlabs/php_codesniffer
  - travis_retry composer require codeclimate/php-test-reporter --dev
  - travis_retry composer require sensiolabs/security-checker:50.x-dev --dev
  - travis_retry composer install --prefer-dist --no-interaction

notifications:
    email: false

script:
  - vendor/bin/phpcs --colors -p --standard=PSR2 --encoding=utf-8 -n src/
  - vendor/bin/phpunit --coverage-text --coverage-clover=build/logs/clover.xml
  - ln -s build/logs/clover.xml coverage.xml
  - vendor/bin/test-reporter
  - vendor/bin/security-checker security:check composer.lock
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN


